version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - internal
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
networks:
    internal:
        driver: bridge
